INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (001,'BANCO DO BRASIL S/A', '00.000.000/0001-91', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (002,'BANCO CENTRAL DO BRASIL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (003,'BANCO DA AMAZONIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (004,'BANCO DO NORDESTE DO BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (007,'BANCO NAC DESENV. ECO. SOCIAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (008,'BANCO MERIDIONAL DO BRASIL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (020,'BANCO DO ESTADO DE ALAGOAS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (021,'BANCO DO ESTADO DO ESPIRITO SANTO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (022,'BANCO DE CREDITO REAL DE MINAS GERAIS SA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (024,'BANCO DO ESTADO DE PERNAMBUCO', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (025,'BANCO ALFA S/A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (026,'BANCO DO ESTADO DO ACRE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (027,'BANCO DO ESTADO DE SANTA CATARINA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (028,'BANCO DO ESTADO DA BAHIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (029,'BANCO DO ESTADO DO RIO DE JANEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (030,'BANCO DO ESTADO DA PARAIBA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (031,'BANCO DO ESTADO DE GOIAS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (032,'BANCO DO ESTADO DO MATO GROSSO S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (033,'BANCO DO ESTADO DE SAO PAULO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (034,'BANCO DO ESADO DO AMAZONAS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (035,'BANCO DO ESTADO DO CEARA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (036,'BANCO DO ESTADO DO MARANHAO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (037,'BANCO DO ESTADO DO PARA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (038,'BANCO DO ESTADO DO PARANA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (039,'BANCO DO ESTADO DO PIAUI S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (041,'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (047,'BANCO DO ESTADO DE SERGIPE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (048,'BANCO DO ESTADO DE MINAS GERAIS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (059,'BANCO DO ESTADO DE RONDONIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (070,'BANCO DE BRASILIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (077,'BANCO INTER S.A', '00.416.968/0001-01', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (102,'XP INVESTIMENTOS', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (104,'CAIXA ECONOMICA FEDERAL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (106,'BANCO ITABANCO S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (107,'BANCO BBM S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (109,'BANCO CREDIBANCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (116,'BANCO B.N.L DO BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (148,'MULTI BANCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (151,'CAIXA ECONOMICA DO ESTADO DE SAO PAULO', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (153,'CAIXA ECONOMICA DO ESTADO DO R.G.SUL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (165,'BANCO NORCHEM S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (166,'BANCO INTER-ATLANTICO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (168,'BANCO C.C.F. BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (175,'CONTINENTAL BANCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (184,'BBA - CREDITANSTALT S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (199,'BANCO FINANCIAL PORTUGUES', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (200,'BANCO FRICRISA AXELRUD S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (201,'BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (204,'BANCO S.R.L S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (205,'BANCO SUL AMERICA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (206,'BANCO MARTINELLI S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (208,'BANCO PACTUAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (210,'DEUTSCH SUDAMERIKANICHE BANK AG', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (211,'BANCO SISTEMA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (212,'BANCO MATONE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (213,'BANCO ARBI S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (214,'BANCO DIBENS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (215,'BANCO AMERICA DO SUL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (216,'BANCO REGIONAL MALCON S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (217,'BANCO AGROINVEST S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (218,'BS2', '71.027.866/0001-34', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (219,'BANCO DE CREDITO DE SAO PAULO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (220,'BANCO CREFISUL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (221,'BANCO GRAPHUS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (222,'BANCO AGF BRASIL S. A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (223,'BANCO INTERUNION S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (224,'BANCO FIBRA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (225,'BANCO BRASCAN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (228,'BANCO ICATU S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (229,'BANCO CRUZEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (230,'BANCO BANDEIRANTES S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (231,'BANCO BOAVISTA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (232,'BANCO INTERPART S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (233,'BANCO MAPPIN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (234,'BANCO LAVRA S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (235,'BANCO LIBERAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (236,'BANCO CAMBIAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (237,'BANCO BRADESCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (239,'BANCO BANCRED S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (240,'BANCO DE CREDITO REAL DE MINAS GERAIS S.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (241,'BANCO CLASSICO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (242,'BANCO EUROINVEST S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (243,'BANCO STOCK S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (244,'BANCO CIDADE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (245,'BANCO EMPRESARIAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (246,'BANCO ABC ROMA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (247,'BANCO OMEGA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (249,'BANCO INVESTCRED S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (250,'BANCO SCHAHIN CURY S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (251,'BANCO SAO JORGE S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (252,'BANCO FININVEST S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (254,'BANCO PARANA BANCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (255,'MILBANCO S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (256,'BANCO GULVINVEST S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (258,'BANCO INDUSCRED S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (260,'NUBANK S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (261,'BANCO VARIG S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (262,'BANCO BOREAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (263,'BANCO CACIQUE', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (264,'BANCO PERFORMANCE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (265,'BANCO FATOR S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (266,'BANCO CEDULA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (267,'BANCO BBM-COM.C.IMOB.CFI S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (275,'BANCO REAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (277,'BANCO PLANIBANC S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (282,'BANCO BRASILEIRO COMERCIAL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (290,'PagSeguro Internet S.A.', '08.561.701/0001-01', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (291,'BANCO DE CREDITO NACIONAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (294,'BCR - BANCO DE CREDITO REAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (295,'BANCO CREDIPLAN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (300,'BANCO DE LA NACION ARGENTINA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (302,'BANCO DO PROGRESSO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (303,'BANCO HNF S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (304,'BANCO PONTUAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (308,'BANCO COMERCIAL BANCESA S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (318,'BANCO B.M.G. S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (320,'BANCO INDUSTRIAL E COMERCIAL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (323,'MercadoPago.com Representações Ltda.', '10.573.521/0001-91', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (332,'Órama DTVM S.A.', '13.293.225/0001-25', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (332,'Acesso Soluções de Pagamento S.A.', '13.140.088/0001-99', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (336,'BANCO C6 S.A.', '31.872.495/0001-72', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (341,'BANCO ITAU S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (346,'BANCO FRANCES E BRASILEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (347,'BANCO SUDAMERIS BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (351,'BANCO BOZANO SIMONSEN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (353,'BANCO GERAL DO COMERCIO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (356,'ABN AMRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (366,'BANCO SOGERAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (369,'PONTUAL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (370,'BEAL - BANCO EUROPEU PARA AMERICA LATINA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (372,'BANCO ITAMARATI S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (375,'BANCO FENICIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (376,'CHASE MANHATTAN BANK S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (388,'BANCO MERCANTIL DE DESCONTOS S/A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (389,'BANCO MERCANTIL DO BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (392,'BANCO MERCANTIL DE SAO PAULO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (394,'BANCO B.M.C. S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (399,'BANCO BAMERINDUS DO BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (409,'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (412,'BANCO NACIONAL DA BAHIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (415,'BANCO NACIONAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (420,'BANCO NACIONAL DO NORTE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (422,'BANCO SAFRA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (424,'BANCO NOROESTE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (434,'BANCO FORTALEZA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (453,'BANCO RURAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (456,'BANCO TOKIO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (464,'BANCO SUMITOMO BRASILEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (466,'BANCO MITSUBISHI BRASILEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (472,'LLOYDS BANK PLC', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (473,'BANCO FINANCIAL PORTUGUES S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (477,'CITIBANK N.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (479,'BANCO DE BOSTON S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (480,'BANCO PORTUGUES DO ATLANTICO-BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (483,'BANCO AGRIMISA S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (487,'DEUTSCHE BANK S.A - BANCO ALEMAO', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (488,'BANCO J. P. MORGAN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (489,'BANESTO BANCO URUGAUAY S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (492,'INTERNATIONALE NEDERLANDEN BANK N.V.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (493,'BANCO UNION S.A.C.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (494,'BANCO LA REP. ORIENTAL DEL URUGUAY', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (495,'BANCO LA PROVINCIA DE BUENOS AIRES', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (496,'BANCO EXTERIOR DE ESPANA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (498,'CENTRO HISPANO BANCO', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (499,'BANCO IOCHPE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (501,'BANCO BRASILEIRO IRAQUIANO S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (502,'BANCO SANTANDER S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (504,'BANCO MULTIPLIC S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (505,'BANCO GARANTIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (600,'BANCO LUSO BRASILEIRO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (601,'BFC BANCO S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (602,'BANCO PATENTE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (604,'BANCO INDUSTRIAL DO BRASIL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (607,'BANCO SANTOS NEVES S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (608,'BANCO OPEN S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (610,'BANCO V.R. S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (611,'BANCO PAULISTA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (612,'BANCO GUANABARA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (613,'BANCO PECUNIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (616,'BANCO INTERPACIFICO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (617,'BANCO INVESTOR S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (618,'BANCO TENDENCIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (621,'BANCO APLICAP S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (622,'BANCO DRACMA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (623,'BANCO PANAMERICANO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (624,'BANCO GENERAL MOTORS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (625,'BANCO ARAUCARIA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (626,'BANCO FICSA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (627,'BANCO DESTAK S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (628,'BANCO CRITERIUM S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (629,'BANCORP BANCO COML. E. DE INVESTMENTO', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (630,'BANCO INTERCAP S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (633,'BANCO REDIMENTO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (634,'BANCO TRIANGULO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (635,'BANCO DO ESTADO DO AMAPA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (637,'BANCO SOFISA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (638,'BANCO PROSPER S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (639,'BIG S.A. - BANCO IRMAOS GUIMARAES', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (640,'BANCO DE CREDITO METROPOLITANO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (641,'BANCO EXCEL ECONOMICO S/A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (643,'BANCO SEGMENTO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (645,'BANCO DO ESTADO DE RORAIMA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (647,'BANCO MARKA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (648,'BANCO ATLANTIS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (649,'BANCO DIMENSAO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (650,'BANCO PEBB S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (652,'BANCO FRANCES E BRASILEIRO SA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (653,'BANCO INDUSVAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (654,'BANCO A. J. RENNER S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (655,'BANCO VOTORANTIM S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (656,'BANCO MATRIX S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (657,'BANCO TECNICORP S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (658,'BANCO PORTO REAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (702,'BANCO SANTOS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (705,'BANCO INVESTCORP S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (707,'BANCO DAYCOVAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (711,'BANCO VETOR S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (713,'BANCO CINDAM S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (715,'BANCO VEGA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (718,'BANCO OPERADOR S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (719,'BANCO PRIMUS S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (720,'BANCO MAXINVEST S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (721,'BANCO CREDIBEL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (722,'BANCO INTERIOR DE SAO PAULO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (724,'BANCO PORTO SEGURO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (725,'BANCO FINABANCO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (726,'BANCO UNIVERSAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (728,'BANCO FITAL S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (729,'BANCO FONTE S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (730,'BANCO COMERCIAL PARAGUAYO S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (731,'BANCO GNPP S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (732,'BANCO PREMIER S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (733,'BANCO NACOES S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (734,'BANCO GERDAU S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (735,'BANCO NEON', '', 1);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (736,'BANCO UNITED S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (737,'THECA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (738,'MARADA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (739,'BGN', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (740,'BCN BARCLAYS', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (741,'BRP', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (742,'EQUATORIAL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (743,'BANCO EMBLEMA S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (744,'THE FIRST NATIONAL BANK OF BOSTON', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (745,'CITIBAN N.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (746,'MODAL S\A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (747,'RAIBOBANK DO BRASIL', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (748,'SICREDI', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (749,'BRMSANTIL SA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (750,'BANCO REPUBLIC NATIONAL OF NEW YORK (BRA', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (751,'DRESDNER BANK LATEINAMERIKA-BRASIL S/A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (752,'BANCO BANQUE NATIONALE DE PARIS BRASIL S', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (753,'BANCO COMERCIAL URUGUAI S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (755,'BANCO MERRILL LYNCH S.A', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (756,'BANCO COOPERATIVO DO BRASIL S.A.', '', 0);
INSERT INTO `Banks` (`BankId`, `Name`, `Document`, `IsDeleted`) VALUES (757,'BANCO KEB DO BRASIL S.A.', '', 0);