name: Labeling new issue

on:
  issues:
      types: ['opened', 'edited']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: Renato66/auto-label@v2.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
