name: Link checker

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
    schedule:
        - cron: 0 0 * * 0

concurrency:
    group: links-checker
    cancel-in-progress: true

jobs:
    link-checker:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v7

            - name: Check for relevant file changes
              uses: dorny/paths-filter@v4
              id: filter
              if: github.event_name == 'pull_request'
              with:
                  filters: |
                      relevant:
                          - 'data/**'
                          - '**/*.md'

            - name: Restore lychee cache
              if: github.event_name != 'pull_request' || steps.filter.outputs.relevant == 'true'
              uses: actions/cache@v5
              with:
                  path: .lycheecache
                  key: cache-lychee-${{ github.sha }}
                  restore-keys: cache-lychee-

            - name: Attach WireGuard connection
              if: github.event_name != 'pull_request' || steps.filter.outputs.relevant == 'true'
              shell: bash
              run: |
                  sudo apt install resolvconf
                  sudo apt install wireguard
                  echo "${{ secrets.WIREGUARD_CONFIG }}" > wg0.conf
                  sudo chmod 600 wg0.conf
                  sudo wg-quick up ./wg0.conf

            - name: Run lychee
              if: github.event_name != 'pull_request' || steps.filter.outputs.relevant == 'true'
              uses: lycheeverse/lychee-action@v2.8.0
              id: lychee
              with:
                  args: '--root-dir "$(pwd)" --cache --max-cache-age 1d .'

            - name: Detach WireGuard connection
              shell: bash
              if: always() && (github.event_name != 'pull_request' || steps.filter.outputs.relevant == 'true')
              run: sudo wg-quick down ./wg0.conf

            - name: Create issue
              if: always() && github.event_name != 'pull_request' && steps.lychee.outputs.exit_code != 0
              uses: peter-evans/create-issue-from-file@v6
              with:
                  title: 🔗✅ Link checker report
                  labels: |
                      🐛 bug
                      🔗 link checker
                      good first issue
                      help wanted
                      hacktoberfest
                  content-filepath: ./lychee/out.md

            - name: Update PR with comment
              uses: mshick/add-pr-comment@v3
              if: always() && github.event_name == 'pull_request' && steps.filter.outputs.relevant == 'true' && steps.lychee.outputs.exit_code != 0
              with:
                  refresh-message-position: true
                  message-id: 'link-checker-result'
                  message-path: ./lychee/out.md
