name: Label based on PR size

on:
  pull_request:
  pull_request_target:
  workflow_dispatch:

jobs:
  size-label:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: size-label
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          ) || (
            github.event_name == 'workflow_dispatch'
          )
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
