name: Label based on PR size

on:
  pull_request:

jobs:
  size-label:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
